name: Build and Deploy Jupyter Notebooks to GitHub Pages

on:
  push:
    branches:
      - main  # or replace with your default branch


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: statml
        environment-file: environment.yml  # Replace with your conda environment file
        python-version: 3.8
        auto-activate-base: true

    - name: Convert Jupyter Notebooks to HTML
      shell: bash -l {0}  # This makes sure the shell is login shell, which can recognize `conda activate`
      run: |
        conda activate statml
        jupyter nbconvert --to html **/*.ipynb  # Convert all notebooks to HTML
        mkdir docs; mv **/*.html docs
        python .github/workflows/build_index.py

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        # Upload entire repository
        path: 'docs'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2